version: "3"

services:
  kotlin-demo-localstack:
    image: localstack/localstack:0.12.9
    container_name: kotlin-demo-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8010}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8010
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-southeast-1
    volumes:
      - my-datavolume:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

  kotlin-demo-redis:
    image: redis
    container_name: kotlin-demo-redis
    ports:
      - "6379:6379"
    volumes:
      - my-datavolume:/data
    networks:
      - backend

  kotlin-demo-dynamodb-admin:
    depends_on:
      - kotlin-demo-localstack
    image: aaronshaf/dynamodb-admin
    container_name: kotlin-demo-dynamodb-admin
    ports:
      - 8042:8001
    environment:
      - DYNAMO_ENDPOINT=http://kotlin-demo-localstack:4566
    networks:
      - backend

  kotlin-demo-redis-commander:
    container_name: kotlin-demo-redis-commander
    hostname: kotlin-demo-redis-commander
    depends_on:
      - kotlin-demo-redis
    image: rediscommander/redis-commander:latest
    #    restart: always
    environment:
      - REDIS_HOSTS=local:kotlin-demo-redis:6379
    ports:
      - "8030:8081"
    networks:
      - backend

volumes:
  my-datavolume:

networks:
  backend: